name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v1
        with:
          version: latest # most recent stable

      - name: Check formatting
        run: zig fmt --check .

  test:
    name: Test / Zig ${{ matrix.zig-version }} / ${{ matrix.os}}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      matrix:
        zig-version: [0.14.0]
        os: [ubuntu-latest, macos-latest, windows-latest]
        allow-fail: [false]
        include:
          - zig-version: master
            os: ubuntu-latest
            allow-fail: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kcov
        if: matrix.os == 'ubuntu-latest'
        run: |
          URL=https://github.com/SimonKagstrom/kcov/releases/download/$KCOV_VERSION/kcov-amd64.tar.gz
          curl -L "$URL" | sudo tar xvzf - -C /
        env:
          KCOV_VERSION: v42

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - name: Run tests
        run: |
          zig build test
